
export type StoreRecord = {
  store: {
    storeId: string;
    storeName: string;
    storeOldId: number;
    status: string;
    isArchived: boolean;
    city: string;
    state: string;
    region: string;
    accountName: string;
    accountNumber: string;
    bankName: string;
    storeEmail: string;
    phoneNumber: string;
    address: string;
    createdAt: string;
    updatedAt: string;
  };
  auditLogs: Array<{
    user: {
      userId: string;
      firstName: string;
      lastName: string;
      email: string;
      role: string;
      createdAt: string;
      updatedAt: string;
    };
    action: string;
    previousData: {
      city: string;
      state: string;
      region: string;
      status: string;
      address: string;
      channel: string | null;
      partner: string;
      storeId: string;
      bankCode: string;
      bankName: string;
      latitude: number;
      clusterId: number;
      createdAt: string;
      longitude: number;
      storeName: string;
      storeOpen: string;
      updatedAt: string;
      isArchived: boolean;
      storeClose: string;
      storeEmail: string;
      storeErpId: string | null;
      storeOldId: number;
      accountName: string;
      phoneNumber: string;
      accountNumber: string;
    };
    newData: {
      city: string;
      state: string;
      region: string;
      status: string;
      address: string;
      channel: string | null;
      partner: string;
      storeId: string;
      bankCode: string;
      bankName: string;
      latitude: number;
      clusterId: number;
      createdAt: string;
      longitude: number;
      storeName: string;
      storeOpen: string;
      updatedAt: string;
      isArchived: boolean;
      storeClose: string;
      storeEmail: string;
      storeErpId: string | null;
      storeOldId: number;
      accountName: string;
      phoneNumber: string;
      accountNumber: string;
    };
    changes: {
      city: string;
      state: string;
      region: string;
      address: string;
      partner: string;
      storeId: string;
      bankCode: string;
      bankName: string;
      latitude: number;
      clusterId: number;
      longitude: number;
      storeName: string;
      storeOpen: string;
      storeClose: string;
      storeEmail: string;
      accountName: string;
      phoneNumber: string;
      accountNumber: string;
    };
    createdAt: string;
  }>;
};

