export type CustomerRecord = {
	customerId: string;
	firstName: string;
	lastName: string;
	email: string;
	bvn: string;
	dob: string;
	inputtedDob: string;
	dobMisMatch: boolean;
	createdAt: string;
	updatedAt: string;
	customerLoanDiskId: string;
	channel: string;
	bvnPhoneNumber: string;
	mainPhoneNumber: string;
	mbeId: string;
	monoCustomerConnectedCustomerId: string;
	fullName?: string;
	age?: number;
	status?: string;
	Wallet?: {
		wallet_id: string;
		accountNumber: string;
		bankName: string;
		dva_id: number;
		accountName: string;
		bankId: number;
		currency: string;
		cust_code: string;
		cust_id: number;
		userId: string;
		created_at: string;
		updated_at: string;
		customerId: string;
	};
	WalletBalance?: {
		balanceId: string;
		userId: string;
		balance: number;
		lastBalance: number;
		created_at: string;
		updated_at: string;
		customerId: string;
	};
	TransactionHistory?: Array<{
		transactionHistoryId: string;
		amount: number | null;
		paymentType: string | null;
		prevBalance: number | null | string;
		newBalance: number | null | string;
		paymentReference: string | null;
		extRef: string | null;
		currency: string;
		channel: string;
		charge: number | null;
		chargeNarration: string | null;
		senderBank: string | null;
		senderAccount: string | null;
		recieverBank: string | null;
		recieverAccount: string | null;
		paymentDescription: string | null;
		paid_at: string;
		createdAt: string;
		updatedAt: string;
		userid: string;
		customersCustomerId: string;
	}>;
	CustomerKYC?: Array<{
		kycId: string;
		customerId: string;
		houseNumber: string;
		streetAddress: string;
		nearestBusStop: string;
		localGovernment: string;
		state: string;
		town: string;
		occupation: string;
		businessName: string;
		applicantBusinessAddress: string;
		applicantAddress: string;
		source: string;
		phone2: string;
		phone3: string;
		phone4: string;
		phone5: string;
		refName2: string;
		refName3: string;
		refName4: string;
		refName5: string;
		phoneApproved: string;
		generalStatus: string;
		generalComment: string;
		createdAt: string;
		updatedAt: string;
		status2Comment: string | null;
		status3Comment: string | null;
		channel: string;
		phone2Status: string;
		phone3Status: string;
		updated_by?: {
			adminid: string;
			password: string;
			userid: string;
			mbeId?: string;
			inviteStatus: string;
			user?: {
				userId: string;
				firstName: string;
				lastName: string;
				email: string;
				dob?: string;
				gender?: string;
				role: string;
				referralCode?: string;
				telephoneNumber: string;
				profile_picture?: string;
				otp?: string;
				tokenVersion: number;
				accountStatus: string;
				isActive: boolean;
				otpExpiry?: string;
				createdAt: string;
				updatedAt: string;
				accountType: string;
				companyName?: string;
				companyAddress?: string;
				companyState?: string;
				companyCity?: string;
				companyLGA?: string;
			};
		};
		updated_by_id?: string;
	}>;
	CustomerAccountDetails?: Array<{
		customerAccountDetailsId: string;
		customerId: string;
		accountNumber: string;
		bankCode: string;
		channel: string;
		createdAt: string;
		updatedAt: string;
		bankID: number;
		bankName: string;
	}>;
	CustomerMandate?: Array<{
		customerMandateId: string;
		customerId: string;
		mandateId: string;
		status: string;
		monoCustomerId: string;
		mandate_type: string;
		debit_type: string;
		ready_to_debit: boolean;
		approved: boolean;
		start_date: string;
		end_date: string;
		reference: string;
		channel: string;
		createdAt: string;
		updatedAt: string;
		message: string;
	}>;
	LoanRecord?: Array<{
		loanRecordId: string;
		customerId: string;
		loanDiskId: string;
		customerLoanDiskId: string;
		lastPoint: string;
		channel: string;
		loanStatus: string;
		createdAt: string;
		updatedAt: string;
		loanAmount: number;
		deviceId: string;
		newDeviceId: string | null;
		downPayment: number;
		insurancePackage: string;
		insurancePrice: number;
		mbsEligibleAmount: number;
		payFrequency: string;
		storeId: string;
		devicePrice: number;
		deviceAmount: number;
		monthlyRepayment: number;
		duration: number;
		interestAmount: number;
		deviceName: string;
		LoanRecordCard: any[];
		store: {
			storeOldId: number;
			storeName: string;
			city: string;
			state: string;
			region: string | null;
			address: string;
			accountNumber: string;
			accountName: string;
			bankName: string;
			bankCode: string;
			phoneNumber: string;
			storeEmail: string;
			longitude: number;
			latitude: number;
			clusterId: number;
			partner: string;
			storeOpen: string;
			storeClose: string;
			createdAt: string;
			updatedAt: string;
			storeId: string;
		};
		device: {
			price: number;
			deviceModelNumber: string;
			SAP: number;
			SLD: number;
			createdAt: string;
			deviceManufacturer: string;
			deviceName: string;
			deviceRam: string | null;
			deviceScreen: string | null;
			deviceStorage: string | null;
			imageLink: string;
			newDeviceId: string;
			oldDeviceId: string;
			sentiprotect: number;
			updatedAt: string;
			deviceType: string;
			deviceCamera: any[];
			android_go: string;
		};
		StoresOnLoan: Array<{
			storeOnLoanId: string;
			storeId: string;
			loanRecordId: string;
			amount: number;
			status: string;
			createdAt: string;
			updatedAt: string;
			channel: string;
			tnxId: string | null;
			sessionId: string | null;
			reference: string | null;
			payChannel: string | null;
			bankUsed: string | null;
		}>;
		DeviceOnLoan: Array<{
			deviceOnLoanId: string;
			deviceId: string;
			loanRecordId: string;
			status: string;
			lockType: string;
			createdAt: string;
			updatedAt: string;
			channel: string;
			imei: string | null;
			newDeviceId: string | null;
			amount: number;
			devicePrice: number;
		}>;
	}>;
	regBy: {
		title: string;
		createdAt: string;
		mbeId: string;
		mbe_old_id: string;
		updatedAt: string;
		firstname: string;
		lastname: string;
		phone: string;
		state: string | null;
		username: string;
		accountStatus: string;
		assignedStoreBranch: string | null;
		bvn: string | null;
		bvnPhoneNumber: string | null;
		channel: string | null;
		dob: string | null;
		email: string | null;
		isActive: boolean;
		otp: string | null;
		otpExpiry: string | null;
		password: string | null;
		role: string;
		tokenVersion: number;
		stores: Array<{
			id: string;
			mbeOldId: string;
			storeOldId: number;
			mbeId: string | null;
			storeId: string | null;
			store: {
				storeOldId: number;
				storeName: string;
				city: string;
				state: string;
				region: string;
				address: string;
				accountNumber: string;
				accountName: string;
				bankName: string;
				bankCode: string;
				phoneNumber: string;
				storeEmail: string;
				longitude: number;
				latitude: number;
				clusterId: number;
				partner: string;
				storeOpen: string;
				storeClose: string;
				createdAt: string;
				updatedAt: string;
				storeId: string;
			};
		}>;
	};
	MonoCustomer?: {
		customerId: string;
		createdAt: string;
		updatedAt: string;
		email: string;
		name: string;
		connectedCustomerId: string;
		monourl: string;
		tempAccountId: string | null;
		CustomerAccounts: any[];
	};
};

// Repayment Schedule Types
export interface RepaymentScheduleSummary {
	totalSchedules: number;
	completedSchedules: number;
	pendingSchedules: number;
	partialSchedules: number;
	overdueSchedules: number;
	totalDue: number;
	totalPaid: number;
	remainingBalance: number;
	percentagePaid: string;
}

export interface RepaymentDetail {
	id: string;
	transactionHistoryId: string;
	amount: number;
	channel: string;
	paymentReference: string;
	paymentDescription: string;
	createdAt: string;
}

export interface RepaymentScheduleItem {
	id: string;
	installmentNumber: number;
	dueDate: string;
	amount: number;
	amountPaid: number;
	status: "PENDING" | "PARTIAL" | "COMPLETED";
	completedAt: string | null;
	repayments: RepaymentDetail[];
}

export interface RepaymentScheduleLoan {
	loanRecordId: string;
	customerId: string;
	loanAmount: number;
	monthlyRepayment: number;
	duration: number;
	loanStatus: string;
	channel: string;
	createdAt: string;
	updatedAt: string;
}

export interface RepaymentScheduleData {
	loanId: string;
	loan: RepaymentScheduleLoan;
	schedules: RepaymentScheduleItem[];
	summary: RepaymentScheduleSummary;
}

export interface RepaymentScheduleResponse {
	statusCode: number;
	statusType: string;
	message: string;
	data: RepaymentScheduleData;
	responseTime: string;
}